name: Samurai CPU test with Beltrami

on:
  push:
    branches: [ "main" ]

jobs:
  docker-build-and-test:
    runs-on: gh-arc-runners-samurai-runner
    steps:
    - name: Checkout code from a pull request or push
      uses: actions/checkout@v3
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Get the current date for an image tag
      id: date
      run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
    - name: Buildah Action 
      uses: redhat-actions/buildah-build@v2 
      with: 
        image: samurai-kaniko
        tags: ${{ steps.date.outputs.date }} 
        containerfiles: | 
          .docker/Dockererfile 